import {Config,defaults} from "./dsp/types";
export interface Scenario {id:string;name:string;title:string;description:string;question:string;observation:string;config:Partial<Config>;focus?:number}
export const scenarios:Scenario[]=[
  {id:"bandwidth",name:"Bandwidth & pulse duration",title:"See time become bandwidth.",description:"Compress the pulse. Watch its spectrum expand.",question:"What changes when the pulse is twice as short?",observation:"For a fixed Gaussian shape, halving σ doubles bandwidth. Choose fixed energy to expose the corresponding increase in peak amplitude.",config:{}},
  {id:"reflectors",name:"Two nearby reflectors",title:"Resolve what looks like one echo.",description:"Move two echoes together and compare their correlation peaks.",question:"Can the receiver distinguish two arrivals?",observation:"Reduce the echo delay, then shorten the pulse. The approximate monostatic range-resolution scale is c/(2B), while the actual ability to separate peaks depends on pulse shape, SNR and relative amplitude.",config:{count:1,sigma:.4e-9,echoDelay:2e-9,echoGain:.8,snr:20,bits:16,windowSize:64,hop:16,mergeGap:.5e-9,pfa:.0001},focus:201},
  {id:"multipath",name:"Indoor multipath",title:"The strongest path can arrive later.",description:"Inspect a weak direct arrival followed by a stronger reflection.",question:"Which arrival gives an unbiased propagation delay?",observation:"The earliest resolvable path is the timing reference. Selecting the largest peak can overestimate distance. Higher bandwidth helps separate paths, but cannot remove non-line-of-sight propagation bias. The CFAR neighborhood of each strong echo masks the weaker direct path; set First-arrival search-back to 20 ns to recover it.",config:{count:3,pri:128e-9,sigma:.7e-9,echoDelay:12e-9,echoGain:1.6,amplitude:.55,snr:8},focus:70},
  {id:"interference",name:"Narrowband interference",title:"Find the pulse beside the carrier.",description:"A persistent tone cuts across transient broadband energy.",question:"Does the detector follow the tone or the pulses?",observation:"The tone forms a horizontal ridge; short pulses form vertical structures. Raise interference and examine local noise estimates, masking, and ADC saturation. Different detectors have different failure modes.",config:{interference:.18,interferenceOffset:.9e9,snr:5,detector:"os"},focus:64},
  {id:"weak",name:"Weak pulses in noise",title:"Recover timing below the noise.",description:"Compare raw energy with a known-template matched filter.",question:"What prior knowledge does correlation use?",observation:"A matched filter combines samples coherently using a known pulse shape. It can reveal a pulse that is difficult to see in an individual sample or frequency bin. Template mismatch reduces that advantage.",config:{snr:-16,sigma:.6e-9,detector:"ca",pfa:.005},focus:64},
  {id:"overlap",name:"Overlapping pulse trains",title:"From fragments to pulse trains.",description:"Inspect two synthetic sources with overlapping spectra and different intervals.",question:"When does association merge two physical events?",observation:"Time-frequency grouping is a heuristic, not an emitter identity oracle. Change source separation and fragment gap to expose merged events, missed pulses, and incorrect train membership.",config:{secondary:true,secondaryDelay:5e-9,secondaryOffset:.9e9,snr:16,mergeGap:1e-9},focus:66},
  {id:"windows",name:"FFT / STFT tradeoffs",title:"Choose what you can resolve.",description:"Trade temporal localization against frequency discrimination.",question:"Does a larger FFT always reveal more information?",observation:"Window duration sets the information available to each transform. Zero padding gives denser frequency samples, while a longer data window changes resolving power and temporal smearing. The hop sets frame spacing.",config:{secondary:true,secondaryDelay:22e-9,secondaryOffset:.45e9,sigma:2e-9,windowSize:256,fftSize:512,hop:32},focus:75},
  {id:"sampling",name:"Sampling & quantization",title:"Follow the signal through the ADC.",description:"Sample real RF and watch aliasing or quantization change what remains.",question:"What information survives the sampler?",observation:"For ordinary real low-pass sampling, fs must exceed twice the highest admitted frequency. Try 16 GS/s, then 4 GS/s with the anti-alias filter disabled. I/Q uses a translated spectrum with different sampling requirements.",config:{realRF:true,carrier:3e9,sampleRate:16e9,bits:6,snr:25},focus:64},
  {id:"transient",name:"High-amplitude transient",title:"Measure the receiver's recovery.",description:"A large pulse drives limiting, clipping, and a modeled recovery response.",question:"How does a strong transient change the measured spectrum?",observation:"Amplitude clipping creates spectral distortion. Recovery is an illustrative gain-suppression model with an adjustable time constant. UWB describes bandwidth; HPM describes power. These are independent properties.",config:{amplitude:5,limiter:4,fullScale:.7,recovery:7e-9,echoGain:.12,echoDelay:8e-9,snr:30,count:3,pri:128e-9},focus:69},
  {id:"chirp",name:"Long wideband chirp",title:"Wide bandwidth. Long duration.",description:"Compare the transmitted envelope with its compressed correlation response.",question:"Why can a wideband waveform still last many nanoseconds?",observation:"A chirp distributes frequency over time. Its time-bandwidth product can be large; matched filtering produces a much narrower response. Bandwidth permits short pulses but does not force every signal to be short.",config:{family:"chirp",sigma:8e-9,chirpBandwidth:1.2e9,count:3,pri:150e-9,windowSize:64,hop:16,guard:8,snr:16,mergeGap:6e-9},focus:64},
  {id:"ppm",name:"Pulse-position communication",title:"Let timing carry the symbol.",description:"Decode early and late pulse slots with correlation.",question:"How do slot spacing and multipath change decisions?",observation:"Each symbol chooses an early or late arrival slot. The decoder compares correlation peaks using the known symbol clock, without reading transmitted bits. The displayed bits are compared only after decoding.",config:{ppm:true,slot:8e-9,pri:64e-9,count:6,sigma:.6e-9,snr:-8},focus:68},
];
export function scenarioConfig(id:string):Config{return {...defaults,...scenarios.find(s=>s.id===id)?.config};}
export const references=[
  {name:"UWB bandwidth and fractional bandwidth",url:"https://www.ecfr.gov/current/title-47/chapter-I/subchapter-A/part-15/subpart-F/section-15.503"},
  {name:"NIST: UWB ranging and multipath",url:"https://www.nist.gov/ctl/wireless-networks-division/ultra-wideband-location"},
  {name:"STFT and spectrogram definitions",url:"https://www.mathworks.com/help/signal/ref/spectrogram.html"},
  {name:"CFAR statistics and assumptions",url:"https://www.mathworks.com/help/phased/ref/phased.cfardetector2d-system-object.html"},
  {name:"Matched filtering and pulse compression",url:"https://www.mathworks.com/help/signal/ug/radar-pulse-compression.html"},
];
