"use client";
import {useMemo} from "react";
import {Result} from "@/lib/dsp/types";
import {db,interpolate} from "@/lib/dsp/numeric";
import {LinePlot,magnitude,real,Spectrogram} from "./plots";
import {Choice} from "./controls";
import {StageInspector} from "./stage-inspector";
import {cfarExtents} from "@/lib/dsp/detection";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";
import {Checkbox} from "@/components/ui/checkbox";
import {Button} from "@/components/ui/button";
export function ReceiverView({r,stage,advanced,theme,domain,cursor,setCursor,selected,setSelected,shownPulses,togglePulse,showAllPulses,clearPulses,maskMode,setMaskMode,representation,setRepresentation}:{
 r:Result;stage:number;advanced:boolean;theme:string;domain:[number,number];cursor:number;setCursor:(v:number)=>void;
 selected?:number;setSelected:(v:number)=>void;
 shownPulses:number[];togglePulse:(id:number)=>void;showAllPulses:()=>void;clearPulses:()=>void;maskMode:"power"|"mask"|"spots";setMaskMode:(v:"power"|"mask"|"spots")=>void;
 representation:string;setRepresentation:(v:string)=>void;
}){
 const c=r.config,d=r.detection!;
 const plots=useMemo(()=>{
  // RF is synthesized on a band-limited interpolated grid with at least 8 points per cycle of fc + fs/2.
  const factor=representation==="rf"?Math.min(64,2**Math.ceil(Math.log2(Math.max(1,8*(c.carrier+c.sampleRate/2)/c.sampleRate)))):1;
  const rf=factor>1?{iq:interpolate(r.iq,factor),time:Float64Array.from({length:r.time.length*factor},(_,i)=>i/(c.sampleRate*factor))}:{iq:r.iq,time:r.time};
  const selectedSignal=stage===0?r.source:stage===1?r.channel:stage===2?r.front:stage===3?r.adc:r.iq;
  const name=stage===0?"Source":stage===1?"Channel":stage===2?"Front end":stage===3?"ADC":"Receiver I/Q";
  const signal=representation==="iq"?[{name:name+" I",values:real(selectedSignal),color:"var(--blue)"},{name:name+" Q",values:Float64Array.from({length:selectedSignal.length/2},(_,i)=>selectedSignal[2*i+1]),color:"var(--cyan)"}]:
   representation==="rf"?[{name:"Reconstructed RF",values:Float64Array.from(rf.time,(t,i)=>rf.iq[2*i]*Math.cos(2*Math.PI*c.carrier*t)-rf.iq[2*i+1]*Math.sin(2*Math.PI*c.carrier*t)),color:"var(--blue)"}]:
   [{name:"Source envelope",values:magnitude(r.source),color:"var(--cyan)",dashed:true},{name:name+" envelope",values:magnitude(selectedSignal),color:"var(--blue)"}];
  return {time:Float64Array.from(r.time,t=>t*1e9),signalTime:Float64Array.from(rf.time,t=>t*1e9),rate:c.sampleRate*factor,signal,freq:Float64Array.from(r.spectrum.frequency,v=>v/1e9),
   psd:[{name:"Receiver PSD",values:Float64Array.from(r.spectrum.psd,db),color:"var(--cyan)"}],
   correlation:[{name:"Envelope",values:magnitude(r.iq),color:"var(--muted-foreground)"},{name:"Matched-filter amplitude",values:d.matched,color:"var(--amber)"}],
   reconstruction:[{name:"Received I",values:real(r.iq),color:"var(--muted-foreground)"},{name:"Masked iSTFT I",values:real(d.recovered),color:"var(--cyan)"},{name:"Template fit I",values:real(d.fitted),color:"var(--amber)",dashed:true}],
   residual:[{name:"Residual I",values:Float64Array.from({length:r.iq.length/2},(_,i)=>r.iq[2*i]-d.recovered[2*i]),color:"var(--blue)"}],
   integrated:Float64Array.from({length:r.tf.frames},(_,t)=>{let power=0;for(let f=0;f<r.tf.bins;f++)power+=r.tf.power[t*r.tf.bins+f]*r.tf.binSpacing;return power;})
  };
 },[r,stage,representation,c.carrier,c.sampleRate,d]);
 const frame=Math.max(0,Math.min(r.tf.frames-1,Math.round(cursor*1e-9*c.sampleRate/Math.min(c.hop,c.windowSize/2))));
 const slice=useMemo(()=>[{name:"Frame PSD",values:Float64Array.from({length:r.tf.bins},(_,f)=>db(r.tf.power[frame*r.tf.bins+f])),color:"var(--blue)"},{name:"Noise estimate",values:Float64Array.from({length:r.tf.bins},(_,f)=>db(d.noise[frame*r.tf.bins+f])),color:"var(--muted-foreground)",dashed:true},{name:"Threshold",values:Float64Array.from({length:r.tf.bins},(_,f)=>db(d.thresholds[frame*r.tf.bins+f])),color:"var(--amber)"}],[frame,r,d]);
 const freqDomain:[number,number]=[-Math.min(c.sampleRate*.45,Math.max(c.rxBandwidth/2,1.5e9))/1e9,Math.min(c.sampleRate*.45,Math.max(c.rxBandwidth/2,1.5e9))/1e9];
 const active=d.pulses.find(p=>p.id===selected);
 return <>
  <div className="readouts" data-tour="readouts"><div><span>−10 dB source bandwidth</span><strong>{(r.sourceBandwidth/1e9).toFixed(3)} <small>GHz</small></strong></div><div><span>Main-lobe power FWHM</span><strong>{(r.sourceWidth*1e9).toFixed(3)} <small>ns</small></strong></div><div><span>Detected / truth events</span><strong>{d.pulses.length} <small>/ {r.truth.length}</small></strong></div><div><span>Matched-event timing RMSE</span><strong>{Number.isFinite(d.timingRmse)?(d.timingRmse*1e12).toFixed(1):"—"} <small>ps</small></strong></div></div>
  <div className="chart-grid"><section className="plot-card" data-tour="time-domain"><div className="card-heading"><div><span className="section-index">A</span><h2>Time domain</h2></div><div className="compact-choice"><Choice label="Trace" value={representation} options={[{value:"envelope",label:"Envelope"},{value:"iq",label:"I & Q"},{value:"rf",label:"RF from I/Q"}]} onChange={setRepresentation}/></div></div><LinePlot x={representation==="rf"?plots.signalTime:plots.time} series={plots.signal} domain={domain} xLabel="Time (ns)" yLabel={representation==="envelope"?"Envelope (V)":"Voltage (V)"} cursor={cursor} onCursor={setCursor}/>
   <div className="plot-caption">{representation==="rf"?"RF synthesized from I/Q after band-limited interpolation to "+(plots.rate/1e9).toFixed(0)+" GS/s. Interpolation cannot restore bandwidth lost at sampling; use real-RF acquisition to study that loss.":"Extrema-preserving display; processing always uses the full sample record."}</div></section>
   <section className="plot-card" data-tour="spectrum"><div className="card-heading"><div><span className="section-index">B</span><h2>Receiver spectrum</h2></div><span className="micro-label">{(c.carrier/1e9).toFixed(2)} GHz CARRIER</span></div><LinePlot x={plots.freq} series={plots.psd} domain={freqDomain} xLabel="Carrier offset (GHz)" yLabel="PSD (dBV²/Hz)"/><div className="plot-caption">Two-sided Hann-windowed periodogram of the acquired I/Q record.</div></section></div>
  <div className="analysis-grid"><section className="plot-card waterfall" data-tour="spectrogram"><div className="card-heading"><div><span className="section-index">C</span><h2>Time-frequency plane</h2></div><div className="segmented" aria-label="Spectrogram view">{(["power","mask","spots"] as const).map(m=><button key={m} aria-pressed={maskMode===m} className={maskMode===m?"chosen":""} onClick={()=>setMaskMode(m)}>{m==="power"?"Power":m==="mask"?"Detections":"Spots"}</button>)}</div></div>
   <Spectrogram key={theme} result={r} domain={domain} cursor={cursor} onCursor={setCursor} mode={maskMode} selectedPulse={selected} shownPulses={shownPulses} inspect={stage===5||advanced}/>
   <div className="spectrogram-foot"><span>{r.tf.frames} frames · {r.tf.fullBins} FFT · {c.windowSize} window · {Math.min(c.hop,c.windowSize/2)} hop</span><div className="color-legend"><span>{maskMode==="mask"?"0":"−55"}</span><i/><span>{maskMode==="mask"?"1":"0 dB"}</span></div></div>
   {(stage===5||advanced)&&c.detector!=="fixed"&&<CfarLegend r={r}/>}
   <div className="plot-caption">{maskMode==="mask"?"Raw cell detections before minimum-area and persistent-tone rejection.":maskMode==="spots"?"Boxes enclose retained connected components. Select a pulse below to highlight its support.":"Frequency is relative to the carrier. Click the plot to position the linked time cursor."}</div>
   {active&&<div className="plot-caption">P{String(active.id).padStart(2,"0")}: the amber box encloses the spots it was built from; the white cross marks its estimated arrival time and centre frequency, with a vertical bar spanning ±BW₁₀/2.</div>}
  </section><StageInspector key={stage} stage={stage} result={r} advanced={advanced}/></div>
  {(stage===5||advanced)&&<section className="plot-card detail-card"><div className="card-heading"><div><span className="section-index">D</span><h2>Threshold inspection</h2></div><span className="micro-label">FRAME AT {(r.tf.times[frame]*1e9).toFixed(2)} ns</span></div><LinePlot x={Float64Array.from(r.tf.frequencies,v=>v/1e9)} series={slice} domain={freqDomain} xLabel="Carrier offset (GHz)" yLabel="PSD (dBV²/Hz)" height={195}/><div className="plot-caption">Move the time cursor to inspect the noise estimate and threshold in a particular STFT frame. Per-cell Pfa is a model target; measure the achieved rate in Validation.</div></section>}
  <section className="plot-card detail-card" data-tour="pulses"><div className="card-heading"><div><span className="section-index">E</span><h2>Constructed pulses</h2><span className="tag">{d.spots.length} spots → {d.pulses.length} events</span></div><div className="pulse-box-actions"><span className="micro-label">BOXES ON PLANE C</span><Button variant="outline" size="sm" disabled={!d.pulses.length||shownPulses.length===d.pulses.length} onClick={showAllPulses}>Show all</Button><Button variant="ghost" size="sm" disabled={!shownPulses.length&&selected===undefined} onClick={clearPulses}>Clear</Button></div></div>
   <div className="pulse-summary"><span><b className="cyan">{d.matchedCount}</b> truth matches</span><span><b className="amber">{d.missed}</b> missed</span><span><b>{d.falseEvents}</b> unmatched estimates</span><span>±2 ns evaluation gate</span></div>
   <div className="pulse-table"><Table><TableHeader><TableRow><TableHead className="pulse-check-head"><span className="sr-only">Show on time-frequency plane</span></TableHead>{["Pulse","TOA · ns","Width · ns","Peak · V","Center · GHz","BW₁₀ · GHz","Train","Truth / error"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{d.pulses.map(p=><TableRow key={p.id} data-state={p.id===selected?"selected":undefined} onClick={()=>{setSelected(p.id);setCursor(p.time*1e9);}}><TableCell onClick={e=>e.stopPropagation()}><Checkbox checked={shownPulses.includes(p.id)} onCheckedChange={()=>togglePulse(p.id)} aria-label={"Show P"+String(p.id).padStart(2,"0")+" on the time-frequency plane"}/></TableCell><TableCell><button className="pulse-select" onClick={()=>{setSelected(p.id);setCursor(p.time*1e9);}}>P{String(p.id).padStart(2,"0")}</button>{p.firstPath&&<small title="Found by first-arrival search"> · first path</small>}</TableCell><TableCell>{(p.time*1e9).toFixed(3)}</TableCell><TableCell>{(p.width*1e9).toFixed(3)}</TableCell><TableCell>{p.amplitude.toFixed(3)}{p.clipped?" ⚑":""}</TableCell><TableCell>{(p.frequency/1e9).toFixed(3)}</TableCell><TableCell>{(p.bandwidth/1e9).toFixed(3)}</TableCell><TableCell>T{p.train}</TableCell><TableCell>{p.match?p.match+" / "+((p.error??0)*1e12).toFixed(1)+" ps":"Unmatched"}</TableCell></TableRow>)}</TableBody></Table></div>
   {!d.pulses.length&&<p className="empty-message">No pulse candidates survived. Reduce the threshold or minimum spot area to explore why.</p>}
   <div className="plot-caption">{active?"Selected P"+active.id+": spots "+active.spotIds.join(", ")+", ∫|I/Q|²dt ≈ "+(active.energy*1e9).toFixed(3)+" V²·ns, local peak/noise "+active.snr.toFixed(1)+" dB. ":""}Train 1 median PRI: {Number.isFinite(d.pri)?(d.pri*1e9).toFixed(2)+" ns":"insufficient events"}; RMS interval deviation: {Number.isFinite(d.priJitter)?(d.priJitter*1e9).toFixed(2)+" ns":"—"}. Estimates can include false, split or merged events.</div>
  </section>
  <div className="chart-grid detail-card" data-tour="branches"><section className="plot-card"><div className="card-heading"><div><span className="section-index">F</span><h2>Matched-filter branch</h2></div><span className="tag">KNOWN TEMPLATE</span></div><LinePlot x={plots.time} series={plots.correlation} domain={domain} xLabel="Time (ns)" yLabel="Amplitude (V)" cursor={cursor} onCursor={setCursor}/><div className="plot-caption">Correlation uses the selected pulse shape and scale. It does not use source arrival times.</div></section>
   <section className="plot-card"><div className="card-heading"><div><span className="section-index">G</span><h2>Waveform reconstruction</h2></div></div><LinePlot x={plots.time} series={plots.reconstruction} domain={domain} xLabel="Time (ns)" yLabel="I component (V)" cursor={cursor} onCursor={setCursor}/><div className="plot-caption"><span className="cyan">Masked complex iSTFT</span> · <span className="amber">template fit</span>. Received-I/Q normalized error: {(d.reconstructionError*100).toFixed(1)}%. Removing noise also contributes to this error.</div></section></div>
  {(advanced||r.config.snr<0)&&<div className="chart-grid detail-card"><section className="plot-card"><div className="card-heading"><div><h2>Energy-detector branch</h2></div><span className="tag">{d.energyEvents.length} EXCURSIONS</span></div><LinePlot x={plots.time} series={[{name:"Rolling mean power",values:d.energyTrace,color:"var(--blue)"},{name:"Energy threshold",values:Float64Array.from(r.time,()=>d.energyThreshold),color:"var(--amber)",dashed:true}]} domain={domain} xLabel="Time (ns)" yLabel="Mean |I/Q|² (V²)" cursor={cursor} onCursor={setCursor}/><div className="plot-caption">Average over σ; threshold = record median × {c.thresholdDb.toFixed(0)} dB. Each contiguous crossing is an event candidate. This heuristic has no calibrated Pfa and can fragment noisy pulses. Compare with template correlation above.</div></section><section className="plot-card"><div className="card-heading"><div><h2>Frequency-integrated energy</h2></div></div><LinePlot x={Float64Array.from(r.tf.times,t=>t*1e9)} series={[{name:"Displayed-band STFT power",values:plots.integrated,color:"var(--cyan)"}]} domain={domain} xLabel="Time (ns)" yLabel="Σ PSD · Δf (V²)" cursor={cursor} onCursor={setCursor}/><div className="plot-caption">Summing the displayed frequency band collects distributed pulse energy. Time resolution still follows the analysis window; persistent interference also contributes.</div></section></div>}
  {advanced&&<section className="plot-card detail-card"><div className="card-heading"><div><span className="section-index">H</span><h2>Reconstruction residual</h2></div><span className="micro-label">UNMASKED ROUND TRIP {d.unmaskedError.toExponential(1)}</span></div><LinePlot x={plots.time} series={plots.residual} domain={domain} xLabel="Time (ns)" yLabel="Received − reconstructed (V)" cursor={cursor} onCursor={setCursor} height={180}/><div className="plot-caption">A spot list does not contain phase. The iSTFT retains original complex coefficients and applies the detected mask. The template fit adds an explicit pulse-family assumption.</div></section>}
 </>;
}
// Legend for the CFAR neighborhood drawn around the clicked cell, with its physical extents.
function CfarLegend({r}:{r:Result}){
 const c=r.config,n=cfarExtents(r.tf,c),frame=Math.min(c.hop,c.windowSize/2)/c.sampleRate*1e9,mhz=r.tf.binSpacing/1e6;
 const size=(frames:number,bins:number)=>"±"+(frames*frame).toFixed(1)+" ns × ±"+(bins*mhz).toFixed(0)+" MHz";
 // Three aligned columns: swatch, region, half-extent; the explanation follows as a note.
 return <div className="cfar-legend" role="group" aria-label="CFAR neighborhood legend">
  <i className="swatch cut"/><span>Cell under test</span><span/>
  <i className="swatch guard"/><span>Guard (excluded)</span><span className="cfar-extent">{size(n.timeGuard,n.freqGuard)}</span>
  <i className="swatch train"/><span>Training edge</span><span className="cfar-extent">{size(n.timeOuter,n.freqOuter)}</span>
  <p className="cfar-note">Cells between the amber and teal edges {c.detector==="os"?"are ranked; the 75th percentile sets":"are averaged into"} the noise estimate. Click the plane to move the neighborhood; record edges truncate it.</p>
 </div>;
}
