import katex from "katex";
import type {Result} from "@/lib/dsp/types";
export const stages=[
 {name:"Source",title:"Construct the waveform",text:"A complex envelope describes amplitude and phase around the selected carrier. Pulse-train timing is generated independently of the receiver. The monocycle and doublet are derivatives of a Gaussian envelope.",formula:"s(t)=\\Re\\{u(t)e^{j2\\pi f_c t}\\}",detail:"Gaussian u(t) = A exp(−t²/(2σ²)). Width here is the power FWHM of its main lobe. Fixed energy preserves ∫|u|²dt when changing σ within the same pulse family; carrier cycles do not set the envelope bandwidth."},
 {name:"Channel",title:"Add propagation and interference",text:"Delayed copies represent multipath. The second source has a different carrier offset and pulse interval. A continuous tone and complex Gaussian noise are added before the receiver.",formula:"r(t)=\\sum_k a_k u(t-\\tau_k)+i(t)+n(t)",detail:"Record SNR is primary pulse-train mean power divided by input complex-noise power over the full 512 ns. It is not the instantaneous pulse-peak SNR or post-filter SNR. A stronger reflected path can bias a largest-peak time estimator."},
 {name:"Front end",title:"Limit the admitted signal",text:"A symmetric FIR models the receiver passband. Gain and radial amplitude limiting act before the ADC. An optional exponential gain-recovery model illustrates how a large transient affects following samples.",formula:"u_{\\mathrm{out}}[n]=g[n]\\,(h*u)[n]",detail:"The 63-tap passband FIR and 95-tap anti-alias FIR are applied to a 64 GS/s reference with zero extension and compensated group delay. This is an offline sampled-signal model, not an electromagnetic antenna or hardware-damage solver."},
 {name:"ADC / I/Q",title:"Sample, quantize, translate",text:"The reference waveform is filtered and downsampled to the selected rate. The ADC clips each real component to its voltage range and rounds it to a signed integer code. Real-RF mode also mixes to I/Q and low-pass filters the result.",formula:"\\Delta_q=\\frac{2V_{FS}}{2^{b}},\\quad q[n]=\\Delta_q\\,\\mathrm{round}(v[n]/\\Delta_q)",detail:"I/Q mode is a complex-envelope acquisition equivalent. Real RF explicitly uses Re{u exp(j2πfct)} before sampling and a 2 exp(−j2πfct) digital mixer. Delays of all symmetric FIRs are compensated. Intentional undersampling can destroy recoverable quadrature information."},
 {name:"FFT / STFT",title:"Localize energy in time and frequency",text:"Each frame multiplies the complex samples by an analysis window and takes an FFT. The spectrogram is squared magnitude; the full complex transform is retained for reconstruction.",formula:"X_m[k]=\\sum_n x[n]w[n-mH]e^{-j2\\pi kn/N}",detail:"Two-sided PSD is |X|²/(fs Σw²) in V²/Hz. Bin spacing is fs/N; equivalent noise bandwidth is fs Σw²/(Σw)². More zero padding does not improve the window's resolving power. Overlap correlates neighboring frames."},
 {name:"Spot detector",title:"From threshold crossings to spots",text:"Compare each time-frequency cell with a fixed noise-relative threshold or an adaptive CFAR threshold. Connected cells form candidate spots. Minimum area and optional persistent-tone rejection remove some clutter.",formula:"P[m,k]>\\alpha\\,\\widehat{P}_n[m,k]",detail:"CA uses the mean training power. OS uses the 75th percentile and an exponential-noise threshold factor. Time guard/training extents are configurable; frequency guard is 4× the time guard in bins, with 3 outer training bins. The nominal Pfa assumes independent exponential powers; STFT overlap and colored noise can violate it."},
 {name:"Pulse builder",title:"Associate and refine pulse events",text:"Join temporally compatible spot fragments, then refine peaks from the original I/Q samples. Estimate pulse width, local spectrum, energy, and candidate train membership. Select a row below to follow the corresponding samples.",formula:"\\widehat{\\tau}=\\arg\\max_t |x(t)|^2\\ \\text{or}\\ \\arg\\max_t |(x\\star s)(t)|",detail:"Time grouping can merge simultaneous sources. Gaussian-envelope refinement splits peaks only when the intervening valley is below half the weaker peak. Other families use one peak per group, timed from the known-template correlation: a derivative pulse’s |I/Q|² peaks on a lobe ±σ from its center, and a chirp’s envelope is long. Clipped peaks use the center of the ADC-rail plateau. FWHM and spectrum estimates can be biased by overlapping pulses. Candidate trains use frequency consistency, not known source labels."},
];
export function Equation({tex}:{tex:string}){return <div className="equation" dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{throwOnError:false,displayMode:true})}}/>;}
export function StageInspector({stage,result,advanced}:{stage:number;result:Result;advanced:boolean}){
 const s=stages[stage],c=result.config;
 return <aside className="stage-inspector"><p className="eyebrow">INSIDE STAGE {String(stage+1).padStart(2,"0")}</p><h2>{s.title}</h2><p>{s.text}</p><Equation tex={s.formula}/>
  <dl className="inspector-metrics">
   {stage===0?<><div><dt>Carrier</dt><dd>{(c.carrier/1e9).toFixed(2)} GHz</dd></div><div><dt>Single-pulse energy</dt><dd>{(result.sourceEnergy*1e9).toFixed(3)} V²·ns</dd></div><div><dt>−10 dB fraction</dt><dd>{(100*result.sourceBandwidth/c.carrier).toFixed(1)}%</dd></div></>:
   stage===3?<><div><dt>Clipped samples</dt><dd>{result.clipped} / {result.time.length}</dd></div><div><dt>Code step</dt><dd>{(2*c.fullScale/2**c.bits*1e3).toFixed(3)} mV</dd></div><div><dt>Sample interval</dt><dd>{(1e12/c.sampleRate).toFixed(1)} ps</dd></div></>:
   stage===4?<><div><dt>Window duration</dt><dd>{(result.tf.windowDuration*1e9).toFixed(2)} ns</dd></div><div><dt>Frame spacing</dt><dd>{(Math.min(c.hop,c.windowSize/2)/c.sampleRate*1e9).toFixed(2)} ns</dd></div><div><dt>Noise bandwidth</dt><dd>{(result.tf.enbw/1e6).toFixed(1)} MHz</dd></div></>:
   stage>=5?<><div><dt>Retained spots</dt><dd>{result.detection?.spots.length}</dd></div><div><dt>Constructed pulses</dt><dd>{result.detection?.pulses.length}</dd></div><div><dt>Nominal cell Pfa</dt><dd>{c.detector==="fixed"?"Fixed threshold":c.pfa.toExponential(0)}</dd></div></>:
   <><div><dt>Receiver bandwidth</dt><dd>{(c.rxBandwidth/1e9).toFixed(2)} GHz</dd></div><div><dt>Record SNR</dt><dd>{c.snr} dB</dd></div><div><dt>Echo delay</dt><dd>{(c.echoDelay*1e9).toFixed(2)} ns</dd></div></>}
  </dl>
  {advanced&&<div className="graduate-note"><span>GRADUATE NOTE</span><p>{s.detail}</p></div>}
 </aside>;
}
