"use client";
import {useEffect,useRef,useState} from "react";
import type {Config,Result} from "@/lib/dsp/types";
import type {ValidationResult} from "@/lib/dsp/validation";
import {Button} from "@/components/ui/button";
import {Progress} from "@/components/ui/progress";
import {createDspWorker} from "@/lib/dsp/create-worker";
export function ValidationView({config,result}:{config:Config;result:Result}){
 const [validation,setValidation]=useState<ValidationResult>(),[progress,setProgress]=useState(0),[running,setRunning]=useState(false),[error,setError]=useState("");
 const worker=useRef<Worker|null>(null);useEffect(()=>()=>worker.current?.terminate(),[]);
 const run=()=>{
  worker.current?.terminate();setRunning(true);setProgress(0);setError("");
  const w=createDspWorker();worker.current=w;
  w.onmessage=e=>{if(e.data.progress)setProgress(e.data.progress);if(e.data.validation){setValidation(e.data.validation);setRunning(false);w.terminate();}if(e.data.error){setError(e.data.error);setRunning(false);w.terminate();}};
  w.onerror=e=>{setError(e.message);setRunning(false);};w.postMessage({id:1,type:"validate",config,trials:16});
 };
 const stale=validation&&JSON.stringify(validation.config)!==JSON.stringify(config);
 return <div className="learning-view"><div className="learning-lead"><p className="eyebrow">MEASURE THE RECEIVER</p><h2>Test the assumptions against data.</h2><p>Run sixteen reproducible noise realizations using the current controls. Pulse events are scored against source truth, while separate white-noise records estimate per-cell false alarms.</p></div>
  <div className="validation-toolbar"><Button onClick={run} disabled={running}>Run 16-trial experiment</Button>{running&&<Button variant="outline" onClick={()=>{worker.current?.terminate();setRunning(false);}}>Cancel</Button>}<span>{running?progress+" / 16 records complete":stale?"Results belong to previous settings.":validation?"Experiment complete":"Ready"}</span></div>
  {running&&<Progress value={progress/16*100} aria-label="Validation progress"/>}{error&&<p role="alert" className="error-box">{error}</p>}
  {validation&&<><div className="readouts detail-card"><div><span>Empirical event detection</span><strong>{(validation.probability*100).toFixed(1)} <small>%</small></strong></div><div><span>Unmatched events / record</span><strong>{(validation.falseEvents/validation.trials).toFixed(2)}</strong></div><div><span>Noise-only cell false alarms</span><strong>{validation.cellFalseAlarm.toExponential(2)}</strong></div><div><span>Timing RMSE of matches</span><strong>{Number.isFinite(validation.timingRmse)?(validation.timingRmse*1e12).toFixed(1):"—"} <small>ps</small></strong></div></div>
   <div className="lesson-grid"><article className="lesson-card"><h3>Event accounting</h3><p>{validation.matched} of {validation.events} true events matched within ±2 ns; {validation.missed} missed; {validation.falseEvents} estimated events unmatched. Matching is one-to-one. These are finite-sample observations, not a guarantee for other scenes.</p></article><article className="lesson-card"><h3>Requested versus achieved Pfa</h3><p>Requested CFAR Pfa: {validation.requestedPfa.toExponential(1)}. Observed noise-cell rate: {validation.cellFalseAlarm.toExponential(2)}. Overlap and windowing correlate cells; edge handling also changes the training set. Pulse-level false events are a different metric. The fixed-threshold mode has no nominal Pfa target.</p></article><article className="lesson-card"><h3>Numerical reconstruction</h3><p>Worst unmasked normalized reconstruction error: {validation.roundTripError.toExponential(2)}. Masked reconstruction intentionally removes coefficients, so it should not be expected to reproduce the noisy input exactly.</p></article><article className="lesson-card"><h3>Measured computation cost</h3><p>Mean complete pipeline: {validation.meanMs.toFixed(0)} ms. Slowest record: {validation.maxMs.toFixed(0)} ms. OS-CFAR sorts local training values and can be substantially slower than cell averaging. The simulation runs in a worker so controls remain available.</p></article></div></>}
  <section className="lesson-card detail-card"><h3>Current record checks</h3><dl className="inspector-metrics"><div><dt>Unmasked STFT round-trip relative error</dt><dd>{result.detection?.unmaskedError.toExponential(2)}</dd></div><div><dt>Sample count / physical duration</dt><dd>{result.time.length} / 512 ns</dd></div><div><dt>Clipped ADC samples</dt><dd>{result.clipped}</dd></div><div><dt>Computation time</dt><dd>{result.elapsed.toFixed(0)} ms</dd></div></dl></section>
  <section className="lesson-card detail-card"><h3>Model boundaries</h3><p>The channel is a linear superposition of delayed copies plus additive noise and interference. Front-end filtering is an offline FIR approximation with compensated group delay. Limiting and recovery are illustrative nonlinear receiver models. Source bandwidth uses an isolated modeled pulse; estimated pulse bandwidth uses a local Hann-windowed spectrum. Neither represents a calibrated radiated-emission test.</p><p>Ground truth is excluded from waveform detection, spot grouping and pulse estimation. It enters only scoring and the displayed transmitted-symbol comparison. Coincident sources and weak multipath can remain unresolved.</p></section>
 </div>;
}
